### PR TITLE
Add Electron Output

### PR DESCRIPTION
**Pull request by malte-christian**
This pull request wraps the kiwiirc output with electron.

Things left to do:
- [x] prevent opening of developer tools (https://github.com/kiwiirc/kiwiirc-desktop/blob/master/src/index.js#L147)
- [ ] desktop item and icons

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
This is excellent. Didn't know you could produce electron so simply... You've blown my mind.

Can you remove the formatting changes and indentation changes, or add them in a separate commit?

**Comment by malte-christian** [comment]
Force pushed the PR with auto formatting removed.

**Comment by MatthewCroughan** [comment]
Is it possible to inline the patch into the flake rather than to include it as a separate file? I'm unsure if this is actually possible, but it would be much neater!

**Comment by malte-christian** [comment]
Yes, that's possible. I've updated the PR.

**Pull request merged**
